// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccessToken() {
  return window['go']['main']['App']['GetAccessToken']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function StartLogin(arg1) {
  return window['go']['main']['App']['StartLogin'](arg1);
}
