// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function GetAccessToken() {
  return window['go']['main']['App']['GetAccessToken']();
}

export function GetAvatar() {
  return window['go']['main']['App']['GetAvatar']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetDiscordID() {
  return window['go']['main']['App']['GetDiscordID']();
}

export function GetFinanceSummary(arg1) {
  return window['go']['main']['App']['GetFinanceSummary'](arg1);
}

export function GetGlobalName() {
  return window['go']['main']['App']['GetGlobalName']();
}

export function GetMemberSince() {
  return window['go']['main']['App']['GetMemberSince']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetTasksDue(arg1) {
  return window['go']['main']['App']['GetTasksDue'](arg1);
}

export function GetTransactions() {
  return window['go']['main']['App']['GetTransactions']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}

export function UpdateTransaction(arg1, arg2) {
  return window['go']['main']['App']['UpdateTransaction'](arg1, arg2);
}
