// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccessToken():Promise<string>;

export function IsAuthenticated():Promise<boolean>;

export function Logout():Promise<void>;

export function StartLogin(arg1:string):Promise<void>;
