// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {main} from '../models';

export function CreateTask(arg1:main.TaskInput):Promise<main.Task>;

export function CreateTransaction(arg1:main.TransactionInput):Promise<main.Transaction>;

export function DeleteTask(arg1:string):Promise<void>;

export function DeleteTransaction(arg1:string):Promise<void>;

export function GetAccessToken():Promise<string>;

export function GetAvatar():Promise<string>;

export function GetCategories():Promise<Array<string>>;

export function GetDiscordID():Promise<string>;

export function GetFinanceSummary(arg1:string):Promise<main.FinanceSummary>;

export function GetGlobalName():Promise<string>;

export function GetTasks():Promise<Array<main.Task>>;

export function GetTransactions():Promise<Array<main.Transaction>>;

export function GetUsername():Promise<string>;

export function IsAuthenticated():Promise<boolean>;

export function Logout():Promise<void>;

export function StartLogin():Promise<void>;

export function UpdateTask(arg1:string,arg2:main.TaskInput):Promise<void>;

export function UpdateTaskStatus(arg1:string,arg2:string):Promise<void>;

export function UpdateTransaction(arg1:string,arg2:main.TransactionInput):Promise<void>;
