// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EjectCheat():Promise<string>;

export function GetCheatConfig():Promise<main.CheatConfig>;

export function GetStatus():Promise<Record<string, any>>;

export function InjectCheat():Promise<string>;

export function UpdateCheatConfig(arg1:main.CheatConfig):Promise<string>;
