// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EjectCheat() {
  return window['go']['main']['App']['EjectCheat']();
}

export function GetCheatConfig() {
  return window['go']['main']['App']['GetCheatConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InjectCheat() {
  return window['go']['main']['App']['InjectCheat']();
}

export function UpdateCheatConfig(arg1) {
  return window['go']['main']['App']['UpdateCheatConfig'](arg1);
}
