// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsSecureBootEnabled() {
  return window['go']['main']['App']['IsSecureBootEnabled']();
}

export function SetSecureBoot(arg1) {
  return window['go']['main']['App']['SetSecureBoot'](arg1);
}
