// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsSecureBootEnabled():Promise<boolean>;

export function SetSecureBoot(arg1:boolean):Promise<string>;
